//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking.BE.model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public class Address
    {
  
        public int address_id { get; set; }
        public int mix_id { get; set; }
        [DisplayName("Address")]
        public string address1 { get; set; }

        [DisplayName("City")]
        public string city { get; set; }

        [DisplayName("State")]
        public string state { get; set; }

        [DisplayName("ZipCode")]
        [Required(ErrorMessage = "Please Enter ZipCode")]
        public string zipcode { get; set; }

        // 1 for user
        // 0 for dealer
        public int role { get; set; }
    
        public virtual City CitName { get; set; }
        public virtual Customer CustomerName { get; set; }
        public virtual Dealer DealerName { get; set; }
        public virtual State StateName { get; set; }
    }
}
