//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int pid { get; set; }
        public int uid { get; set; }
        public string name { get; set; }
        public string category { get; set; }
        public decimal price { get; set; }
        public int quantity { get; set; }
        public string short_desc { get; set; }
        public string long_desc { get; set; }
        public byte[] small_img { get; set; }
        public byte[] large_img { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
